# -*- coding: utf-8 -*-
"""SmartCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CscTaJI-JZsi7ve0S31vb305mSCbHZmo
"""

# Minor Project-1
#Console based smart application

import numpy as np

def menu():
  print("\n--- Smart Calculator ---")
  print("1. Addition")
  print("2. Substraction")
  print("3. Multiplication")
  print("4. Division")
  print("5. Power")
  print("6. Module")
  print("7. Exit")

def get_numbers():
  count = int(input("How many numbers "))
  numbers = []

  for i in range(count):
    num = float(input("Enter number: "))
    numbers.append(num)

  return numbers

def addition(nums):
  arr = np.array(nums) #Numpy used
  return np.sum(arr)

def substraction(nums):
  result = nums[0]
  for i in range(1, len(nums)):
    result = result - nums[i]
  return result

def multiplication(nums):
  result = 1
  for i in nums :
    result = result * i
  return result

def division(nums):
  result = nums[0]
  for i in range(1, len(nums)):
    if nums[i] == 0:
      print("Error. Division by zero is not allowed")
      return None
    result = result / nums[i]
  return result

def power(nums):
  result = nums[0]
  for i in range(1, len(nums)):
    result = result ** nums[i]
  return result

def modulus(nums):
  result = nums[0]
  for i in range(1, len(nums)):
    result = result % nums[i]
  return result

while True:
  menu()
  choice = input("Enter your choice:")

  if choice == '1' or choice == '2' or choice == '3' or choice == '4' or choice == '5' or choice == '6' :
    nums = get_numbers()

    if len(nums) == 0:
      print("No number Entered")
    else:
      if choice == '1':
        result = addition(nums)
      elif choice == '2':
        result = substraction(nums)
      elif choice == '3':
        result = multiplication(nums)
      elif choice == '4':
        result = division(nums)
      elif choice == '5':
        result = power(nums)
      elif choice == '6':
        result = modulus(nums)

      if result is not None :
        print("Result: ", result)

  else:
    print("Invalid choice")

  cont = input("Do you want to continue? (Y/N): ")
  if cont != 'Y':
    print("Calculator stoped")
    break